module.exports.config = {
  name: "emojireply_pro",
  version: "3.0.0",
  hasPermssion: 0,
  credits: "Jahid",
  description: "200+ Emoji auto funny reply (no fallback)",
  commandCategory: "noprefix",
  usages: "auto",
  cooldowns: 2
};

module.exports.handleEvent = async function({ api, event }) {
  const msg = event.body;
  if (!msg) return;

  // ✅ only single emoji
  const onlyEmojiRegex = /^\p{Emoji}$/u;
  if (!onlyEmojiRegex.test(msg.trim())) return;

  const emojiReplies = {

    // 😄 faces
    "😀": "এত খুশি কিসের? লটারি পাইছস নাকি? 😏",
    "😃": "হাসি দেখে মনে হচ্ছে কিছু গোলমাল আছে 😆",
    "😄": "হাসতে হাসতে wifi বন্ধ হয়ে যাবে 😂",
    "😁": "দাঁত দেখানো competition নাকি? 😬",
    "😆": "হাসতে থাক, oxygen শেষ হবে 😏",
    "😅": "নাটক করছস নাকি tension লুকাচ্ছস? 😂",
    "🤣": "কমেডি সার্কাস শুরু হইছে 🤡",
    "😂": "থাম না ভাই, মাটি ফাটাইয়া হাসতেছিস 😭",
    "🙂": "এই হাসিটা fake লাগে 😏",
    "🙃": "উল্টা মানুষ হয়ে গেছিস নাকি? 🤣",
    "😉": "চোখ মারিস কেন? প্ল্যান আছে? 😏",
    "😊": "ভদ্র সাজার চেষ্টা করতেছিস 😆",
    "😇": "এত নির্দোষ কেউ না 😏",
    "🥰": "love love mood 😍",
    "😍": "crush দেখছস বুঝি 😏🔥",
    "🤩": "স্টার দেখে পাগল হয়ে গেছিস 🌟😂",
    "😘": "kiss দিবি নাকি air service 😆",
    "😗": "এই ঠোঁট দিয়ে কি করবি? 😏",
    "😋": "খিদা পাইছে? খাইতে দেই? 😂",
    "😜": "জিহ্বা বাহির কইরা লাভ নাই 😝",
    "🤪": "পাগল mode full ON 🤯",
    "😝": "জিহ্বা বের করে cool ভাব নিচ্ছস 😆",
    "🤑": "টাকা দেখলেই চোখ চকচক 💸",
    "🤗": "আলিঙ্গন দিবি নাকি ফাঁদ পাতছস 🤣",
    "🤭": "হাসি চাপতেছস কেন? 😏",
    "🤫": "secret রাখছস নাকি 😏",
    "🤔": "এত ভাবছস কেন? brain overheat 😂",
    "🤐": "চুপ কেন? ধরা খাইছস? 😆",
    "🤨": "এই expression সন্দেহজনক 😏",
    "😐": "emotion নাই? robot নাকি 🤖",
    "😑": "life boring নাকি? 😴",
    "😶": "মুখ বন্ধ কেন? কথা বল 😆",
    "😏": "এই হাসিটা dangerous 😈",
    "😒": "attitude বেশি হয়ে গেছে 😏",
    "🙄": "চোখ ঘুরাইলে network ধরবে? 📶😂",
    "😬": "ভয় পাইছস নাকি 😆",
    "🤥": "মিথ্যা বলছস clearly 🤥😂",
    "😌": "শান্তি পাইলি নাকি? 😏",
    "😔": "sad story শুরু 😢",
    "😪": "ঘুমাইতে যা 😴",
    "🤤": "লালা ঝরতেছে 🤤 খাবার দে 😂",
    "😴": "ঘুমন্ত ভাল্লুক 🐻😂",
    "😷": "ডাক্তার লাগবে 😷💊",
    "🤒": "জ্বর আসছে মনে হয় 😆",
    "🤕": "মাথায় কে মারছে? 🤣",
    "🤢": "এত নোংরা ভাব কেন 🤮",
    "🤮": "খাবার খারাপ ছিল বুঝি 😂",
    "🥴": "মাতাল হয়ে গেছস নাকি 🍺",
    "😵": "brain crash হয়ে গেছে 🤯",
    "🤯": "মাথা উড়ে গেছে 💥",
    "😎": "style মারতেছস 😏🔥",
    "🤓": "পড়ুয়া ভাই 📚😂",
    "🧐": "detective mode ON 🔍",
    "😕": "confuse হয়ে গেছস 😵",
    "😟": "tension নে কেন? 😆",
    "🙁": "মুখ বাঁকা করিস না 😂",
    "☹️": "sad face 😢",
    "😮": "shock খাইছস নাকি 😳",
    "😯": "বিস্ময় level max 😆",
    "😲": "এত অবাক কেন 😏",
    "😳": "লজ্জা পাচ্ছস 😏",
    "🥺": "cute acting বন্ধ কর 😭",
    "😦": "ভয় পাস নাকি 😨",
    "😧": "এত ভয় কেন 😂",
    "😨": "ghost দেখছস নাকি 👻",
    "😰": "ঘামতেছস tension এ 😂",
    "😥": "sad but silent 😢",
    "😢": "কান্দিস না 😭",
    "😭": "নদী বানায় ফেললি 😂",
    "😱": "ভূত! 👻😂",
    "😖": "কষ্ট পাচ্ছস 😏",
    "😣": "pain mode ON 😆",
    "😞": "মন খারাপ 😢",
    "😓": "tension overload 🤯",
    "😩": "life tough 😂",
    "😫": "আর পারতেছস না 🤣",
    "🥱": "হাই তুলছস 😴",
    "😤": "রাগলে cute লাগতেছস 😂",
    "😡": "angry bird 🐦🔥",
    "🤬": "গালি দিবি নাকি rap 🎤😂",

    // ❤️ symbols
    "❤️": "love attack ❤️🔥",
    "💔": "heart break 💔 sad 😢",
    "💕": "double love 😏",
    "💖": "cute love 💖",
    "💘": "arrow লেগে গেছে 🏹😂",
    "💝": "gift love 🎁",
    "💞": "couple mood 😏",
    "💓": "heart beat fast 😆",
    "💗": "pink love 💗",
    "💙": "blue love 😏",
    "💚": "green signal 😆",
    "💛": "yellow love 😂",
    "🖤": "dark love 😈",

    // 🐶 animals
    "🐶": "কুকুর loyalty আছে? 😂",
    "🐱": "বিড়াল mood 😼",
    "🐭": "ইঁদুর হয়ে গেছস 🐭😂",
    "🐹": "cute hamster 🐹",
    "🐰": "খরগোশ speed 🐰💨",
    "🦊": "চালাক শিয়াল 😏",
    "🐻": "ভাল্লুক mode 🐻",
    "🐼": "পান্ডা lazy 😂",
    "🐸": "ব্যাঙ ডাক দে 🐸",
    "🐵": "বানর 😂🍌",
    "🦁": "lion but attitude fake 😆",
    "🐯": "tiger mode 🐯🔥",
    "🐨": "koala sleep 😴",
    "🐔": "মুরগি ডাক 🐔😂",
    "🐧": "penguin style 😎",
    "🐦": "পাখি উড় 🐦💨",
    "🐤": "baby chick 🐤",
    "🐺": "wolf vibe 😈",
    "🐗": "বন্য শূকর 😂",
    "🐴": "ঘোড়া দৌড় 🐎💨",

    // 🍔 food
    "🍔": "burger attack 🤤",
    "🍕": "pizza lover 🍕🔥",
    "🍟": "fries unlimited 😂",
    "🌭": "hotdog time 🌭",
    "🍿": "movie + popcorn 🎬",
    "🍩": "donut lover 🍩",
    "🍫": "chocolate 😍",
    "🍬": "candy kid 😂",
    "🍭": "lollipop 🍭😏",
    "🍉": "তরমুজ ফাটবে 😂",
    "🍌": "banana 🍌🤣",
    "🍎": "apple 🍎😏",
    "🍇": "angur kha 😂",
    "🍓": "strawberry 🍓😍",
    "🥭": "mango season 🥭🔥",
    "🍍": "ananas 😂",
    "🥥": "narikel vibe 😆",

    // ⚽ activity
    "⚽": "football khel 😏",
    "🏏": "cricket hero 🤣",
    "🏀": "basket fail 😂",
    "🎮": "gamer noob 😏",
    "🎧": "music mood 🎧",
    "🎤": "gaibi naki chillabi 😂",
    "🎬": "movie hero 🤣",
    "🎲": "ludo harbi 😂",
    "🎯": "target miss 😆",

    // 🚗 objects
    "🚗": "car race 🚗💨",
    "🚀": "rocket ureee 🚀",
    "✈️": "flight mode 😂",
    "📱": "mobile addict 📱",
    "💻": "hacker 😂",
    "⌚": "time waste ⌚😆",
    "🔋": "battery low 🔋😂",
    "💡": "idea 💡😏",
    "🔑": "key haraiya gese 😂",
    "🚪": "door close 😂"
  };

  if (emojiReplies[msg]) {
    return api.sendMessage(emojiReplies[msg], event.threadID, event.messageID);
  }

};

module.exports.run = function() {};
